# -*- coding: utf-8 -*-
"""ENGR121_absenteeism_project_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12z9sKWe5ojWrg33sHm0DzyhKv5pJgMWU

# Project Data Exploration: Absenteeism at Work

Oscar Alonso, Jeremy Buban, Joanna Rashid, Kahlyn Smith  
Group Term Project  
ENGR 121 Fall 2020

Last modified October 15, 2020

[Link to Google Colab Notebook](https://colab.research.google.com/drive/12z9sKWe5ojWrg33sHm0DzyhKv5pJgMWU?usp=sharing)

## Problem Statement and Background
When employees are absent from work, firms lose out on production, sometimes employees lose wages, and society loses overall productivity.  Since there are many stakeholders affected by workplace absences, an exploration of the factors which contribute to or co-occur with absences would be instructive.  Such information might inform firms’ employee benefit design, operational organization, and even hiring practices.  Analysis of this data might also influence the design of government social programs and public health initiatives.  This analysis might also yield interesting findings that either support or dispel common misconceptions about the reliability of workers of a particular type.

## Data source
UCI Machine Learning Repository, Absenteeism at work Data Set
(n.d.). Retrieved from https://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work#

The database was created with records of absenteeism at work from July 2007 to July 2010 at a courier company in Brazil.


> *The data set allows for several new combinations of attributes and attribute exclusions, or the modification of the attribute type (categorical, integer, or real) depending on the purpose of the research.The data set (Absenteeism at work - Part I) was used in academic research at the Universidade Nove de Julho - Postgraduate Program in Informatics and Knowledge Management. (archive.ics.uci.edu)*

## Data Flaws/Weaknesses and Cleaning

Fortunately, this dataset does not have missing values or messy date data. The data cleaning required for this data set will be minimal. However, this data set has only numeric values many of which are codes for strings values rather than continuous or discrete values.  This makes our initial statistics, histograms, and violin plot meaningless for some attributes.  This data does not immediately lend itself to regression analysis. 

Some attributes require context to interpret. One example is the transportation expense, this value can vary depending on context of the person being transported. Some people can take public transport, walk to work, or even carpool. Something like this can skew data sets and result in dirty data which would need cleaning.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#data is hosted on github for ease of use of this notebook by multiple users
url = 'https://raw.githubusercontent.com/joannarashid/work_absenteeism/master/Absenteeism_at_work.csv'
df = pd.read_csv(url, sep = ';')

df.head()

"""Data types present in this data set:"""

df.info()

"""## Basic Data Characteristics

Below is a preliminary data exploration of attributes in this dataset and their relationship to the variable of interest, "Absenteeism time in hours."

In general, no single atribute has a very high correlation coefficient.  Coefficients are only useful for dummy and continuous variables.  The histograms and violin plots rendered below are only meaningful for attributes that have continuous numeric data.  The scatter plots rendered below are are not very useful.  However, they do reveal that the independent variable, "Absenteeism time in hours," is not entirely continuous.  It looks like those values are integers that are multiples of 5 or 10.

### Descriptive statistics
"""

df.describe()

"""Constructing a coefficient matrix and displaying just the coefficents of "Absenteeism time in hours.":"""

corr_df = df.corr(method ='pearson') 
corr_df["Absenteeism time in hours"]

"""### Histograms

On first glance (considering only variables with truly numeric values), we can see that height, disciplinary failure, son(whether a person has children or not), and day of the week have coefficeints with the greatest magnitude.
"""

df.hist(figsize=(15, 10))
plt.tight_layout()

"""### Scatterplots

Scatter plots of all variables plotted against our variable of interest, "Absenteeism time in hours."
"""

for column in df:
  plt.figure()
  plt.subplot(1, 1, 1)
  plt.scatter(df['Absenteeism time in hours'], df[column])
  plt.xlabel('Absentee time in hours')
  plt.ylabel(str(column))

"""These scatter plots helped us see that the "Absenteeism time" variable is not continuous.

###Violin plots
"""

for column in df:
  g = sns.FacetGrid(df)
  g.map(sns.violinplot, column)

"""## Surprises

It is suprising that having children and/or pets is not very closely correlated with absenteeism.  In fact, these factors were slightly negatively correlated with work absence.  The relatively low coefficient values suggest that no single employee attribute is a major determinant of absenteeism.  It was also surprising that employee absences were spread roughly evenly accross the week.  We expected them to be heavily skewed towards the beginning and end of the workweek.

### Next Steps

The following variables are catagorical and will need to be converted to or duplicated as strings for further more meaningful data visualization and use of cluster analysis.

*   Reason for absence
*   Season
*   Day of the week
*   Month

For "reason for absence" instead of converting to string values, we will create a dictionary of absence reasons.

We will use cluster analysis and random forest analysis to look for groups of attributes that together are associated with work absences.  We can also look at attributes that are associated with specific reasons for work absence.

We will use multi-variate regression analysis to evaluate these attributes' joint significance.

Once we have identified jointly significant attributes, we will use faceted data visualization to visualize the relationships between three variables at a time.

We will do additional data visualization to illustrate clusers.
"""

